kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mysql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  nfs:
    path: /mnt/kube/mysql
    server: 192.168.100.80
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mysql
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp
    tier: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
      tier: mysql
  template:
    metadata:
      labels:
        app: wp
        tier: mysql
    spec:
      volumes:
        - name: mysql-vol
          persistentVolumeClaim:
            claimName: pvc-mysql
      containers:
      - image: mysql:5.6
        name: mysql
        volumeMounts:
          - name: mysql-vol
            mountPath: /var/lib/mysql
        ports:
          - containerPort: 3306 
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
---
kind: Service
apiVersion: v1
metadata:
  name: wp-mysql
  labels:
    app: wp
spec:
  selector:
    app: wp
    tier: mysql
  type: ClusterIP
  ports:
    - port: 3306
