kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-wordpress
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /mnt/kube/wordpress
    server: 192.168.100.80
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wordpress
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp
    tier: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
      tier: wordpress
  template:
    metadata:
      labels:
        app: wp
        tier: wordpress
    spec:
      volumes:
        - name: wordpress-vol
          persistentVolumeClaim:
            claimName: pvc-wordpress
      containers:
      - image: wordpress
        name: wordpress
        volumeMounts:
          - name: wordpress-vol
            mountPath: /var/www/html
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: wp-mysql
          - name: WORDPRESS_DB_PASSWORD
            value: password
---
kind: Service
apiVersion: v1
metadata:
  name: wp-wordpress
  labels:
    app: wp
spec:
  selector:
    app: wp
    tier: wordpress
  type: NodePort
  ports:
    - port: 80
      nodePort: 31776
